FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /tmp

RUN apt -y update && apt -y upgrade && apt -y install wget 

RUN wget https://apt.kitware.com/kitware-archive.sh 
RUN bash /tmp/kitware-archive.sh

RUN apt -y update && apt -y install --no-install-recommends git \
                cmake \
                ninja-build \
                gperf \
                ccache \
                dfu-util \
                device-tree-compiler \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-tk \
                python3-wheel \
                xz-utils \
                file \
                make \
                gcc \
                gcc-multilib \
                g++-multilib \
                libsdl2-dev
